name: CI

on:
  push:
    tags:
      - v*
    branches:
      - '**'

  pull_request:
    branches:
      - '**'

jobs:
  workflow:
    name: Lint/Test

    env:
      NODE_ENV: ci
    strategy:
      matrix:
        go-version: [ 1.19.x ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{matrix.go-version}}

      - name: Checkout Code Base
        uses: actions/checkout@v3

      - name: GolangCI Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.48.0
          only-new-issues: true
          skip-go-installation: true

      - name: Go Test
        run: go test ./... -short